---

- hosts: local
  tasks:
    - name: Install Oh My Zsh
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    - name: Install p10k
      ansible.builtin.shell:
        cmd: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
    - name: Use p10k
      replace:
        path: ~/.zshrc
        regexp: 'robbyrussell'
        replace: "powerlevel10k/powerlevel10k"
