---

- hosts: local
  tasks:
    - name: Git checkout pyenv
      ansible.builtin.git:
        repo: 'https://github.com/pyenv/pyenv.git'
        dest: /home/{{ user }}/.pyenv
    - name: Append pyenv cmds
      blockinfile:
        state: present
        insertafter: EOF
        dest: /home/{{ user }}/.zshrc
        marker: "## add lines for pyenv ANSIBLE MANAGED BLOCK ##"
        content: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"
